# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f98c5781-6741-493c-89c4-d420c14c8e9b";
      fsType = "ext4";
    };

 fileSystems."/mnt/external" =
   { device = "/dev/disk/by-uuid/7375a35b-acbb-4e8b-bd86-089d4610dc43";
     fsType = "ext4";
   };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E763-49A4";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking = {
  #   useDHCP = false;
  #   interfaces.enp58s0u1u.ipv4.addresses = [
  #     { address = "10.10.1.11"; prefixLength = 16; }
  #   ];
  #   defaultGateway = "10.10.1.1";
  #   nameservers = ["10.0.0.1"];
  # };
  
  # networking = {
  #   useDHCP = lib.mkDefault true;
  #   interfaces.enp0s20f0u2u4c2 = {
  #     useDHCP = false;
  #     ipv4.addresses = [
  #       { address = "10.10.1.11"; prefixLength = 16; }
  #     ];
  #   };
  #   interfaces.enp58s0u1u = {
  #     useDHCP = false;
  #     ipv4.addresses = [
  #       { address = "10.10.1.11"; prefixLength = 16; }
  #     ];
  #   };
  #   defaultGateway = "10.10.1.1";
  #   nameservers = ["10.0.0.1"];
  # };

  # networking.interfaces.enp58s0u1u.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # Audio
  hardware.pulseaudio.enable = true;
  hardware.pulseaudio.support32Bit = true;
}
